[profile.default]
src = "src"
out = "out"
libs = ["lib"]
verbosity = 2 # Show logs by default
gas_reports = ["*"]
viaIR = true
optimizer = true
optimizer_runs = 2
solc= "0.8.24"
#ffi = true
#ast = false
#build_info = true
#extra_output = ["storageLayout"]

[profile.default.optimizer_details]
constantOptimizer = true
yul = true

[profile.default.optimizer_details.yulDetails]
stackAllocation = true
optimizerSteps = ""

#[profile.optimizer_details.yul_details]
#optimizer = false
[fmt]
bracket_spacing = true
int_types = "long"
line_length = 120
multiline_func_header = "all"
quote_style = "double"
tab_width = 4
wrap_comments = true

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
